# mpi
option(ENABLE_RESILIENCE "Enables Resilience Plugin" OFF)
if(ENABLE_RESILIENCE)
    message(STATUS "Resilience Enabled")
    find_library(LZ4_LIB liblz4.so)
    get_filename_component(LZ4_LIB_DIR ${LZ4_LIB} DIRECTORY)
    set(LZ4_LIB_DIR ${LZ4_LIB_DIR} CACHE PATH "Path to the liblz4.so")
    set(LZ4_INCLUDE_DIR ${LZ4_LIB_DIR} CACHE PATH "Path to the lz4.h")
    set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DENABLE_RESILIENCE")
    include_directories(${LZ4_INCLUDE_DIR})
else()
    message(STATUS "Resilience Disabled")
    set(LZ4_LIB "")
endif()